using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace nutriapp.infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddSeedDataClass : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "MeasuredBy",
                columns: table => new
                {
                    Food = table.Column<int>(type: "int", nullable: false),
                    MeasureType = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK__Measured__92FAF591EA351E7B", x => new { x.Food, x.MeasureType });
                    table.ForeignKey(
                        name: "FK__MeasuredB__Measu__08B54D69",
                        column: x => x.MeasureType,
                        principalTable: "MeasureType",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK__MeasuredBy__Food__07C12930",
                        column: x => x.Food,
                        principalTable: "Food",
                        principalColumn: "Id");
                });

            migrationBuilder.InsertData(
                table: "MeasuredBy",
                columns: new[] { "Food", "MeasureType" },
                values: new object[,]
                {
                    { 1, 4 },
                    { 1, 5 },
                    { 1, 11 },
                    { 2, 1 },
                    { 2, 7 },
                    { 3, 4 },
                    { 3, 5 },
                    { 4, 4 },
                    { 4, 5 },
                    { 5, 1 },
                    { 5, 5 },
                    { 6, 1 },
                    { 6, 5 },
                    { 7, 1 },
                    { 7, 5 },
                    { 8, 1 },
                    { 8, 5 },
                    { 9, 1 },
                    { 9, 5 },
                    { 10, 1 },
                    { 10, 5 },
                    { 11, 1 },
                    { 11, 5 },
                    { 12, 1 },
                    { 12, 5 },
                    { 13, 1 },
                    { 13, 6 },
                    { 14, 1 },
                    { 14, 5 },
                    { 15, 1 },
                    { 15, 5 },
                    { 16, 1 },
                    { 16, 7 },
                    { 17, 1 },
                    { 17, 6 },
                    { 18, 1 },
                    { 18, 5 },
                    { 19, 1 },
                    { 19, 5 },
                    { 20, 1 },
                    { 20, 5 },
                    { 21, 1 },
                    { 21, 5 },
                    { 22, 1 },
                    { 22, 5 },
                    { 23, 1 },
                    { 23, 9 },
                    { 24, 1 },
                    { 24, 9 },
                    { 25, 1 },
                    { 25, 6 },
                    { 26, 1 },
                    { 26, 9 },
                    { 27, 1 },
                    { 27, 9 },
                    { 28, 1 },
                    { 28, 5 },
                    { 29, 1 },
                    { 29, 6 },
                    { 30, 1 },
                    { 30, 9 },
                    { 31, 1 },
                    { 31, 6 },
                    { 32, 1 },
                    { 32, 6 },
                    { 33, 1 },
                    { 33, 6 },
                    { 34, 1 },
                    { 34, 6 },
                    { 35, 1 },
                    { 35, 6 },
                    { 36, 1 },
                    { 36, 6 },
                    { 37, 1 },
                    { 37, 5 },
                    { 38, 1 },
                    { 38, 6 },
                    { 39, 1 },
                    { 39, 5 },
                    { 40, 1 },
                    { 40, 6 },
                    { 41, 1 },
                    { 41, 5 },
                    { 42, 1 },
                    { 42, 5 },
                    { 43, 1 },
                    { 43, 6 },
                    { 44, 1 },
                    { 44, 6 },
                    { 45, 1 },
                    { 45, 5 },
                    { 46, 1 },
                    { 46, 6 },
                    { 47, 1 },
                    { 47, 6 },
                    { 48, 1 },
                    { 48, 6 },
                    { 49, 4 },
                    { 49, 11 },
                    { 50, 1 },
                    { 50, 5 },
                    { 51, 1 },
                    { 51, 6 },
                    { 52, 1 },
                    { 52, 6 },
                    { 53, 1 },
                    { 53, 6 },
                    { 54, 1 },
                    { 54, 9 },
                    { 55, 1 },
                    { 55, 5 },
                    { 56, 1 },
                    { 56, 6 },
                    { 57, 4 },
                    { 57, 11 },
                    { 58, 1 },
                    { 58, 5 },
                    { 59, 1 },
                    { 59, 5 },
                    { 60, 1 },
                    { 60, 5 },
                    { 61, 1 },
                    { 61, 5 },
                    { 62, 1 },
                    { 62, 5 },
                    { 63, 1 },
                    { 63, 5 },
                    { 64, 1 },
                    { 64, 5 },
                    { 65, 1 },
                    { 65, 5 },
                    { 66, 1 },
                    { 66, 5 },
                    { 67, 1 },
                    { 67, 5 },
                    { 68, 1 },
                    { 68, 5 },
                    { 69, 1 },
                    { 69, 5 },
                    { 70, 1 },
                    { 70, 5 },
                    { 71, 1 },
                    { 71, 5 },
                    { 72, 1 },
                    { 72, 5 },
                    { 73, 1 },
                    { 73, 5 },
                    { 74, 1 },
                    { 74, 5 },
                    { 75, 1 },
                    { 75, 5 },
                    { 76, 1 },
                    { 76, 5 },
                    { 77, 1 },
                    { 77, 5 },
                    { 78, 1 },
                    { 78, 5 },
                    { 79, 1 },
                    { 79, 6 },
                    { 80, 1 },
                    { 80, 6 },
                    { 81, 1 },
                    { 81, 9 },
                    { 82, 1 },
                    { 82, 6 },
                    { 84, 1 },
                    { 84, 7 },
                    { 85, 1 },
                    { 85, 7 },
                    { 86, 1 },
                    { 86, 5 },
                    { 87, 1 },
                    { 87, 5 },
                    { 88, 1 },
                    { 88, 5 },
                    { 89, 1 },
                    { 89, 5 },
                    { 90, 1 },
                    { 90, 7 },
                    { 91, 1 },
                    { 91, 7 },
                    { 92, 1 },
                    { 92, 7 },
                    { 93, 1 },
                    { 93, 5 },
                    { 94, 1 },
                    { 94, 5 },
                    { 95, 1 },
                    { 95, 5 },
                    { 96, 1 },
                    { 96, 5 },
                    { 97, 1 },
                    { 97, 5 },
                    { 98, 1 },
                    { 98, 5 },
                    { 99, 1 },
                    { 99, 5 },
                    { 100, 1 },
                    { 100, 5 },
                    { 101, 1 },
                    { 101, 5 },
                    { 102, 1 },
                    { 102, 6 },
                    { 103, 1 },
                    { 103, 6 },
                    { 104, 1 },
                    { 104, 5 },
                    { 105, 1 },
                    { 105, 6 },
                    { 106, 1 },
                    { 106, 6 },
                    { 107, 1 },
                    { 107, 6 },
                    { 108, 1 },
                    { 108, 7 },
                    { 109, 1 },
                    { 109, 7 },
                    { 110, 1 },
                    { 110, 8 },
                    { 111, 1 },
                    { 111, 6 },
                    { 112, 4 },
                    { 112, 6 },
                    { 113, 1 },
                    { 113, 8 },
                    { 114, 1 },
                    { 114, 8 },
                    { 115, 1 },
                    { 115, 8 },
                    { 116, 1 },
                    { 116, 10 },
                    { 117, 1 },
                    { 117, 10 },
                    { 118, 1 },
                    { 118, 10 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_MeasuredBy_MeasureType",
                table: "MeasuredBy",
                column: "MeasureType");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "MeasuredBy");
        }
    }
}
